=== dcentelles/uwsimbenchmarks/UWSimBenchmarks/data/benchmark.dtd
<!ELEMENT benchmark (measures,startOn,stopOn,function,sceneUpdater)>

<!ELEMENT measures (time*,collision*,positionError*, distance*, euclideanNorm*)>

<!-- benchmark -->
<!ELEMENT startOn (type,target?,position?)>
<!ELEMENT stopOn (type,target?,position?)>
<!ELEMENT function (#PCDATA)>

<!-- Measures -->
<!ELEMENT time (name,startOn,stopOn)>
<!ELEMENT collision (name,target,startOn,stopOn)>
<!ELEMENT positionError (name,target,position,startOn,stopOn)>
<!ELEMENT distance (name,target,startOn,stopOn)>
<!ELEMENT euclideanNorm (name,groundTruth,target,startOn,stopOn)>

<!-- Trigger -->
<!ELEMENT type (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT position (x,y,z)>


<!-- Position -->
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT groundTruth ((value+)|(camera,target))>
<!ELEMENT camera (#PCDATA)>
<!ATTLIST groundTruth type (constant|cornersFromCamera|centroidFromCamera) #REQUIRED>


<!ELEMENT value (#PCDATA)>

<!-- SceneUpdater -->

<!ELEMENT sceneUpdater (none | sceneFogUpdater)>

<!ELEMENT none EMPTY>

<!ELEMENT sceneFogUpdater (initialFog, finalFog, step, interval)>
<!ELEMENT initialFog (#PCDATA)>
<!ELEMENT finalFog (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT interval (#PCDATA)>

=== dcentelles/uwsimbenchmarks/UWSimBenchmarks/data/visionBenchmarkauto.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="cornersFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="centroidFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function>corners+centroid</function>

  <sceneUpdater> 
    <sceneFogUpdater>
      <initialFog>0</initialFog>
      <finalFog>1.3</finalFog>
      <step>0.05</step>
      <interval>2</interval>
    </sceneFogUpdater>
  </sceneUpdater>

</benchmark>

=== dcentelles/uwsimbenchmarks/UWSimBenchmarks/data/simpleBenchmark.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <time>
      <name>taskTime</name>
      <startOn>
        <type>onInit</type>
      </startOn>
      <stopOn>
         <type>never</type>
      </stopOn>
    </time>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>service</type>
     <target> stopBench </target>
  </stopOn> 
    
  <function>taskTime</function>

  <sceneUpdater> 
    <none />
  </sceneUpdater>

</benchmark>
