=== dcentelles/uwsimbenchmarks/uwsimbenchmarks/data/benchmark.dtd
<!ELEMENT benchmark (measures,startOn,stopOn,function,sceneUpdater)>

<!ELEMENT measures (time*,collision*,positionError*, distance*, euclideanNorm*, objectCenteredOnCam*, reconstruction3D*)>

<!-- benchmark -->
<!ELEMENT startOn (type,target?,position?)>
<!ELEMENT stopOn (type,target?,position?)>
<!ELEMENT function (#PCDATA)>
<!ATTLIST function publishResult (true|false) "false">

<!-- Measures -->
<!ELEMENT time (name,log?,startOn,stopOn)>
<!ELEMENT collision (name,target,log?,startOn,stopOn)>
<!ELEMENT positionError (name,target,position,log?,startOn,stopOn)>
<!ELEMENT distance (name,target,log?,startOn,stopOn)>
<!ELEMENT euclideanNorm (name,groundTruth,target,log?,startOn,stopOn)>
<!ELEMENT objectCenteredOnCam (name,target,camera,log?,startOn,stopOn)>
<!ELEMENT reconstruction3D (name,target, topic, from, levelOfDetail?, log?,startOn,stopOn)>
<!ATTLIST reconstruction3D detailedResultsToGlobals (true|false) "false">

<!-- Trigger -->
<!ELEMENT type (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT position (x,y,z)>


<!-- Position -->
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT log (#PCDATA)>

<!-- Euclidean Norm -->
<!ELEMENT groundTruth ((value+)|(camera,target,publishOn?)|(from,to))>
<!ELEMENT camera (#PCDATA)>
<!ELEMENT publishOn (#PCDATA)>
<!ATTLIST groundTruth type (constant|cornersFromCamera|centroidFromCamera|relativeLocation) #REQUIRED>

<!ELEMENT value (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>

<!-- reconstruction3D -->
<!ELEMENT topic (#PCDATA)>
<!ELEMENT levelOfDetail (#PCDATA)>

<!-- SceneUpdater -->

<!ELEMENT sceneUpdater (none | sceneFogUpdater | currentForceUpdater | armMoveUpdater | repeat | sceneLightUpdater)>

<!ELEMENT none EMPTY>

<!ELEMENT sceneFogUpdater (initialFog, finalFog, step, interval,sceneUpdater?)>
<!ELEMENT currentForceUpdater (initialCurrent, finalCurrent, sphericalDirection, forceVariation, forcePeriod, directionVariation, directionPeriod, random, step, interval, target,sceneUpdater?)>
<!ATTLIST currentForceUpdater publishAsForce (true|false) "false">
<!ELEMENT armMoveUpdater (armPosition+, step, interval, target,sceneUpdater?)>
<!ELEMENT repeat (iterations, interval,sceneUpdater?)>
<!ELEMENT sceneLightUpdater (initialLight, finalLight, step, interval,sceneUpdater?)>

<!ELEMENT armPosition (joint+)>
<!ELEMENT joint (#PCDATA)>
<!ELEMENT initialFog (#PCDATA)>
<!ELEMENT finalFog (#PCDATA)>
<!ELEMENT initialLight (#PCDATA)>
<!ELEMENT finalLight (#PCDATA)>
<!ELEMENT initialCurrent (#PCDATA)>
<!ELEMENT finalCurrent (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT interval (#PCDATA)>
<!ELEMENT iterations (#PCDATA)>

<!-- Current -->
<!ELEMENT sphericalDirection (theta, phi)>
<!ELEMENT directionVariation (theta, phi)>
<!ELEMENT directionPeriod (theta, phi)>
<!ELEMENT theta (#PCDATA)>
<!ELEMENT phi (#PCDATA)>
<!ELEMENT forceVariation (#PCDATA)>
<!ELEMENT forcePeriod (#PCDATA)>
<!ELEMENT random (#PCDATA)>

=== dcentelles/uwsimbenchmarks/uwsimbenchmarks/data/visionBenchmarkauto.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <euclideanNorm>
      <name>corners</name>
      <groundTruth type="cornersFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
	<publishOn> autoInit</publishOn>
      </groundTruth>	
      <target> cornersTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

    <euclideanNorm>
      <name>centroid</name>
      <groundTruth type="centroidFromCamera">
	<camera>bowtech1</camera>
	<target>blackbox</target>
      </groundTruth>	
      <target> centroidTopic </target>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </euclideanNorm>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function publishResult="true">corners+centroid</function>

  <sceneUpdater> 
    <sceneFogUpdater>
      <initialFog>0</initialFog>
      <finalFog>2.0</finalFog>
      <step>0.05</step>
      <interval>5</interval>
    </sceneFogUpdater>
  </sceneUpdater>

</benchmark>

=== dcentelles/uwsimbenchmarks/uwsimbenchmarks/data/reconstruction.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <reconstruction3D>
      <name>reconstruction</name>	
      <target> blackbox </target>
      <topic> /reconstruction </topic>
      <levelOfDetail>0.003</levelOfDetail>
      <log>0.1</log>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </reconstruction3D>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>never</type>
  </stopOn> 
    
  <function publishResult="true">reconstruction</function>

  <sceneUpdater> 
    <sceneFogUpdater>
      <initialFog>0</initialFog>
      <finalFog>2.0</finalFog>
      <step>0.05</step>
      <interval>5</interval>
    </sceneFogUpdater>
  </sceneUpdater>

</benchmark>

=== dcentelles/uwsimbenchmarks/uwsimbenchmarks/data/pipeFollowing.xml
<?xml version="1.0"?>

<!DOCTYPE benchmark SYSTEM "benchmark.dtd" >

<benchmark>
  <measures>

    <time>
      <name>taskTime</name>
      <startOn>
        <type>onInit</type>
      </startOn>
      <stopOn>
         <type>never</type>
      </stopOn>
    </time>

    <pathFollowing>
      <name>pathFollowing</name>
      <target> girona500 </target>
      <topic> path </topic>
      <from> localizedWorld </from>
      <log> 0.1 </log>
      <startOn>
	<type>onInit</type>
      </startOn>
      <stopOn>
	<type>never</type>
      </stopOn>
    </pathFollowing>

  </measures>

  <startOn>
     <type>service</type>
     <target> startBench </target>
  </startOn>

  <stopOn>
     <type>service</type>
     <target> stopBench </target>
  </stopOn> 
    
  <function publishRate="0.5" publishResult="true">taskTime</function>

  <sceneUpdater> 
    <none />
  </sceneUpdater>

</benchmark>
